Description: VPC, Subnet declarations for New Caprica
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha: 
    Type: String
    Description: Git commit SHA
    Default: nocommit
  galacticaIp:
    Type: String
    Description: IP4 address for galactica (or whatever IP address you want to allow)
    Default: 127.0.0.1
    MinLength: 9
    MaxLength: 15
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}$

Resources:
  CreateNewCapricaVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.1.0.0/16'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name
          Value: 'NewCaprica-PublicIngress'
        - Key: PublicIngress
          Value: true
        - Key: PublicEgress
          Value: true
  
  NewCapricaIPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref 'CreateNewCapricaVpc'

  NewCapricaInternetGateway:
    Type: AWS::EC2::InternetGateway

  NewCapricaInternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties: 
      InternetGatewayId: !Ref 'NewCapricaInternetGateway'
      VpcId: !Ref 'CreateNewCapricaVpc'

  NewCapricaMikeSohDBs:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref 'CreateNewCapricaVpc'
      CidrBlock: "10.1.0.0/28"
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: NewCaprica-MikeSoh-Databases-NoPublicEgress
      - Key: PublicEgress
        Value: FALSE

  NewCapricaMikesohCompute:
    Type: AWS::EC2::Subnet
    DependsOn: 'NewCapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateNewCapricaVpc'
      CidrBlock: "10.1.21.0/26"
      Ipv6CidrBlock: !Select [ 0, !Cidr [ !Select [ 0, !GetAtt CreateNewCapricaVpc.Ipv6CidrBlocks ], 4, 64 ]]
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: NewCaprica-MikeSoh-Compute
      - Key: PublicEgress
        Value: TRUE

  NewCapricaGeneralComputeD:
    Type: AWS::EC2::Subnet
    DependsOn: 'NewCapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateNewCapricaVpc'
      CidrBlock: "10.1.100.0/24"
      Ipv6CidrBlock: !Select [ 1, !Cidr [ !Select [ 0, !GetAtt CreateNewCapricaVpc.Ipv6CidrBlocks], 4, 64 ]]
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: NewCaprica-General-Compute-D

  NewCapricaGeneralComputeB:
    Type: AWS::EC2::Subnet
    DependsOn: 'NewCapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateNewCapricaVpc'
      CidrBlock: "10.1.101.0/24"
      Ipv6CidrBlock: !Select [ 2, !Cidr [ !Select [ 0, !GetAtt CreateNewCapricaVpc.Ipv6CidrBlocks], 4, 64 ]]
      AvailabilityZone: 'us-east-1b'
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: NewCaprica-General-Compute-B
  
  NewCapricaFlowLogs:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      ResourceId: !Ref 'CreateNewCapricaVpc'
      ResourceType: VPC
      TrafficType: ALL
      MaxAggregationInterval: 600
      LogGroupName: vpcLogs
      LogDestinationType: cloud-watch-logs
      DeliverLogsPermissionArn: 'arn:aws:iam::426869176820:role/flowlogsRole'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name 
          Value: 'NewCaprica-FlowLog'

  MikesohComputeNaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !GetAtt 'CreateNewCapricaVpc.DefaultNetworkAcl'
      SubnetId: !Ref 'NewCapricaMikesohCompute'

  galacticaSG:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: Retain
    Properties:
      GroupDescription: Allow all traffic from galactica
      GroupName: !Join ['-', [ !Ref 'AWS::StackName', 'galactica All Traffic [managed]' ]]
      VpcId: !Ref 'CreateNewCapricaVpc'
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Join ['', [!Ref 'galacticaIp', '/32'] ]
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'

Outputs:
  NewCapricaVpcId:
    Value: !Ref 'CreateNewCapricaVpc'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'CreateNewCapricaVpc' ]]

  galacticaSGId:
    Value: !GetAtt galacticaSG.GroupId
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'galacticaSG' ]]
