Description: mikesoh-com Network Deployment
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha: 
    Type: String
    Description: Git commit SHA
    Default: nocommit
  DatabasePassword:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Default Password for Database
    Default: '/us-east-1/rds/AdminPassword'
  DatabasePubliclyAvailable:
    Type: String
    Description: Whether the database is available publicly.
    AllowedValues: ['true', 'false']
    Default: false

Conditions:
  AttachPublicRoutes: !Equals [ !Ref 'DatabasePubliclyAvailable', 'true' ]

Resources:
  MikesohStackDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: mariadb
      EngineVersion: '10.6.8'
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      MasterUsername: 'admin'
      MasterUserPassword: !Ref 'DatabasePassword'

      DBInstanceIdentifier: 'mikesoh-com-db-production'
      DBInstanceClass: 'db.t4g.micro'
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp2
      StorageEncrypted: true
      
      AvailabilityZone: 'us-east-1d'
      BackupRetentionPeriod: 7
      DBSubnetGroupName: !Ref MikesohDBSubnetGroup
      PubliclyAccessible: !Ref 'DatabasePubliclyAvailable'
      VPCSecurityGroups:
        - !ImportValue 'mikesoh-com:MikesohStackSG'
        - !ImportValue 'NewCapricaVpc-Deploy:galacticaSG'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: environment
          Value: "testing"

Outputs:
  MikesohStackDatabaseId:
    Value: !Ref 'MikesohStackDatabase'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'MikesohStackDatabase' ]]