Description: mikesoh-com SES E-mail Receiving Ruleset
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha:
    Type: String
    Description: Git commit SHA
    Default: nocommit
  commitShaShort:
    Type: String
    Description: 7-digit git commit SHA
    Default: nocommi

Resources:
  capricaTkReceiptRuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: !Sub
        - 'caprica.tk_ReceiptRuleSet__commit_${gitCommit}'
        - gitCommit: !Ref commitShaShort
  
  capricaTkReceiptRule01:
    Type: AWS::SES::ReceiptRule
    Properties:
      RuleSetName: !Ref capricaTkReceiptRuleSet
      Rule:
        
Outputs:
  capricaTkReceiptRuleSetOutput:
    Value: !Ref 'capricaTkReceiptRuleSet'
    Export:
      Name: !Join [':', [ !Ref 'AWS::StackName', 'caprica-tk-ReceiptRuleSet' ]]