Description: mikesoh-com Network Deployment
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha: 
    Type: String
    Description: Git commit SHA
    Default: nocommit
  DatabasePassword:
    Type: AWS::SSM::Parameter::Value<String>
    Description: Default Password for Database
    Default: '/us-east-1/rds/AdminPassword'
  SshKeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: starbuck-wsl-ubuntu-ed25519-2021.12.23

Resources:
  NewCapricaMikeSohDBsAzD:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue 'NewCapricaVpc-Deploy:CreateNewCapricaVpc'
      CidrBlock: "10.1.0.0/28"
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name
          Value: NewCaprica-MikeSoh-Az1D-Databases-NoPublicEgress
        - Key: PublicEgress
          Value: TRUE
  
  # NewCapricaMikeSohDBsAzDSubnetRouteTable:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties: 
  #     RouteTableId: !ImportValue 'NewCapricaVpc-Deploy:NewCapricaPublicRouteTable'
  #     SubnetId: !Ref NewCapricaMikeSohDBsAzD

  NewCapricaMikeSohDBsAzB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue 'NewCapricaVpc-Deploy:CreateNewCapricaVpc'
      CidrBlock: "10.1.0.16/28"
      AvailabilityZone: 'us-east-1b'
      MapPublicIpOnLaunch: false
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name
          Value: NewCaprica-MikeSoh-Az1B-Databases-NoPublicEgress
        - Key: PublicEgress
          Value: FALSE

  # NewCapricaMikeSohDBsAzBSubnetRouteTable:
  #   Type: AWS::EC2::SubnetRouteTableAssociation
  #   Properties: 
  #     RouteTableId: !ImportValue 'NewCapricaVpc-Deploy:NewCapricaPublicRouteTable'
  #     SubnetId: !Ref NewCapricaMikeSohDBsAzB

  NewCapricaMikesohCompute:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue 'NewCapricaVpc-Deploy:CreateNewCapricaVpc'
      CidrBlock: "10.1.21.0/26"
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Select [ 2, !Cidr [ !ImportValue "NewCapricaVpc-Deploy:NewCapricaIpv6CidrBlock" , 256, 64 ]]
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: true
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name
          Value: NewCaprica-MikeSoh-Compute
        - Key: PublicEgress
          Value: TRUE

  MikesohComputeNaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !ImportValue NewCapricaVpc-Deploy:NewCapricaDefaultAcl
      SubnetId: !Ref 'NewCapricaMikesohCompute'

  NewCapricaMikesohComputeSubnetRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties: 
      RouteTableId: !ImportValue 'NewCapricaVpc-Deploy:NewCapricaPublicRouteTable'
      SubnetId: !Ref NewCapricaMikesohCompute

  MikesohDBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupName: Mikesoh-com-SubnetGroup
      DBSubnetGroupDescription: Mikesoh.com Subnet Group
      SubnetIds:
        - !Ref NewCapricaMikeSohDBsAzD
        - !Ref NewCapricaMikeSohDBsAzB
  
  MikesohStackSG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Security Group for Mikesoh App
      GroupName: !Join ['-', [ !Ref 'AWS::StackName', 'MikesohStack [managed]' ]]
      VpcId: !ImportValue 'NewCapricaVpc-Deploy:CreateNewCapricaVpc'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
  
  MikesohStackSGSelfIngress:
    Type: 'AWS::EC2::SecurityGroupIngress'
    DependsOn: 'MikesohStackSG'
    Properties:
      Description: Allow all traffic from within the Security Group
      GroupId: !Ref 'MikesohStackSG'
      SourceSecurityGroupId: !Ref 'MikesohStackSG'
      IpProtocol: -1
  
  MikesohStackSGSelfEgress:
    Type: 'AWS::EC2::SecurityGroupEgress'
    DependsOn: 'MikesohStackSG'
    Properties:
      Description: Allow all traffic from within the Security Group
      GroupId: !Ref 'MikesohStackSG'
      DestinationSecurityGroupId: !Ref 'MikesohStackSG'
      IpProtocol: -1

  MikesohStackDatabase:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      Engine: mariadb
      EngineVersion: '10.6.8'
      AllowMajorVersionUpgrade: false
      AutoMinorVersionUpgrade: true
      MasterUsername: 'admin'
      MasterUserPassword: !Ref 'DatabasePassword'

      DBInstanceIdentifier: 'mikesoh-com-db-production'
      DBInstanceClass: 'db.t4g.micro'
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageType: gp2
      StorageEncrypted: true
      
      AvailabilityZone: 'us-east-1d'
      BackupRetentionPeriod: 7
      DBSubnetGroupName: !Ref MikesohDBSubnetGroup
      PubliclyAccessible: true
      VPCSecurityGroups:
        - !Ref 'MikesohStackSG'
        - !ImportValue 'NewCapricaVpc-Deploy:galacticaSG'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: environment
          Value: "testing"

  MikesohStackCompute:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: 't3a.small'
      ImageId: 'ami-0cf6c10214cc015c9'
      IamInstanceProfile: 'arn:aws:iam::426869176820:instance-profile/ec2-user-role'
      AvailabilityZone: 'us-east-1d'
      DisableApiTermination: false
      InstanceInitiatedShutdownBehavior: 'stop'
      SubnetId: !Ref 'NewCapricaMikesohCompute'
      KeyName: !Ref 'SshKeyName'

      BlockDeviceMappings:
        - DeviceName: '/dev/sda1'
          Ebs:
            DeleteOnTermination: true
            Encrypted: true
            VolumeSize: 50
            VolumeType: gp3
      
      SecurityGroupIds:
        - !Ref 'MikesohStackSG'
        - !ImportValue 'NewCapricaVpc-Deploy:galacticaSG'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'  

Outputs:
  MikeSohDBsAzDSubnet:
    Value: !Ref 'NewCapricaMikeSohDBsAzD'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'NewCapricaMikeSohDBsAzD' ]]
  
  MikeSohDBsAzBSubnet:
    Value: !Ref 'NewCapricaMikeSohDBsAzB'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'NewCapricaMikeSohDBsAzB' ]]
  
  ExportMikesohDBSubnetGroup:
    Value: !Ref 'MikesohDBSubnetGroup'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'MikesohDBSubnetGroup' ]]

  MikeSohComputeSubnet:
    Value: !Ref 'NewCapricaMikesohCompute'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'NewCapricaMikesohCompute' ]]

  MikesohStackDatabaseId:
    Value: !Ref 'MikesohStackDatabase'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'MikesohStackDatabase' ]]
  
  MikesohStackComputeInstanceId:
    Value: !Ref 'MikesohStackCompute'
    Export:
      Name: !Join [':', [ !Ref 'AWS::StackName', 'MikesohStackCompute' ]]

  ExportMikesohAppSG:
    Value: !Ref MikesohStackSG
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'MikesohStackSG' ]]