Description: mikesoh-com Network Deployment
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha: 
    Type: String
    Description: Git commit SHA
    Default: nocommit

Resources:
  NewCapricaMikeSohDBs:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue 'NewCapricaVpc-Deploy:CreateNewCapricaVpc'
      CidrBlock: "10.1.0.0/28"
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: false
      Tags:
      - Key: Name
        Value: NewCaprica-MikeSoh-Databases-NoPublicEgress
      - Key: PublicEgress
        Value: FALSE

  NewCapricaMikesohCompute:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue 'NewCapricaVpc-Deploy:CreateNewCapricaVpc'
      CidrBlock: "10.1.21.0/26"
      AssignIpv6AddressOnCreation: true
      Ipv6CidrBlock: !Select [ 2, !Cidr [ !ImportValue "NewCapricaVpc-Deploy:NewCapricaIpv6CidrBlock" , 256, 64 ]]
      AvailabilityZone: 'us-east-1d'
      MapPublicIpOnLaunch: true
      Tags:
      - Key: Name
        Value: NewCaprica-MikeSoh-Compute
      - Key: PublicEgress
        Value: TRUE

  MikesohComputeNaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !ImportValue NewCapricaVpc-Deploy:NewCapricaDefaultAcl
      SubnetId: !Ref 'NewCapricaMikesohCompute'


Outputs:
  MikeSohDBsSubnet:
    Value: !Ref 'NewCapricaMikeSohDBs'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'NewCapricaMikeSohDBs' ]]
  
  MikeSohComputeSubnet:
    Value: !Ref 'NewCapricaMikesohCompute'
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'NewCapricaMikesohCompute' ]]