Description: VPC, Subnet, NaCl declaration for Caprica
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha: 
    Type: String
    Description: Git commit SHA
    Default: nocommit

Resources:
  CreateCapricaVpc:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '192.168.253.0/24'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name
          Value: 'NewCaprica-PublicIngress'
        - Key: PublicIngress
          Value: true
        - Key: PublicEgress
          Value: true
  
  CapricaIPv6CidrBlock:
    Type: AWS::EC2::VPCCidrBlock
    Properties:
      AmazonProvidedIpv6CidrBlock: true
      VpcId: !Ref 'CreateCapricaVpc'

  CapricaSubnetA:
    Type: AWS::EC2::Subnet
    DependsOn: 'CapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateCapricaVpc'
      CidrBlock: !Select [ 0, !Cidr [ !GetAtt 'CreateCapricaVpc.CidrBlock', 4, 6 ]]
      Ipv6CidrBlock: !Select [ 0, !Cidr [ !Select [ 0, !GetAtt CreateCapricaVpc.Ipv6CidrBlocks], 4, 64 ]]
      AvailabilityZone: 'us-east-1a'
      Tags:
      - Key: Name
        Value: NewCaprica-A

  CapricaSubnetB:
    Type: AWS::EC2::Subnet
    DependsOn: 'CapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateCapricaVpc'
      CidrBlock: !Select [ 1, !Cidr [ !GetAtt 'CreateCapricaVpc.CidrBlock', 4, 6 ]]
      Ipv6CidrBlock: !Select [ 1, !Cidr [ !Select [ 0, !GetAtt CreateCapricaVpc.Ipv6CidrBlocks], 4, 64 ]]
      AvailabilityZone: 'us-east-1b'
      Tags:
      - Key: Name
        Value: NewCaprica-B

  CapricaSubnetE:
    Type: AWS::EC2::Subnet
    DependsOn: 'CapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateCapricaVpc'
      CidrBlock: !Select [ 2, !Cidr [ !GetAtt 'CreateCapricaVpc.CidrBlock', 4, 6 ]]
      Ipv6CidrBlock: !Select [ 2, !Cidr [ !Select [ 0, !GetAtt CreateCapricaVpc.Ipv6CidrBlocks], 4, 64 ]]
      AvailabilityZone: 'us-east-1e'
      Tags:
      - Key: Name
        Value: NewCaprica-E

  CapricaSubnetF:
    Type: AWS::EC2::Subnet
    DependsOn: 'CapricaIPv6CidrBlock'
    Properties:
      VpcId: !Ref 'CreateCapricaVpc'
      CidrBlock: !Select [ 3, !Cidr [ !GetAtt 'CreateCapricaVpc.CidrBlock', 4, 6 ]]
      Ipv6CidrBlock: !Select [ 3, !Cidr [ !Select [ 0, !GetAtt CreateCapricaVpc.Ipv6CidrBlocks], 4, 64 ]]
      AvailabilityZone: 'us-east-1f'
      Tags:
      - Key: Name
        Value: NewCaprica-F

  CapricaFlowLogs:
    Type: 'AWS::EC2::FlowLog'
    Properties:
      ResourceId: !Ref 'CreateCapricaVpc'
      ResourceType: VPC
      TrafficType: ALL
      MaxAggregationInterval: 600
      LogGroupName: vpcLogs
      LogDestinationType: cloud-watch-logs
      DeliverLogsPermissionArn: 'arn:aws:iam::426869176820:role/flowlogsRole'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'
        - Key: Name 
          Value: 'Caprica-FlowLog'

  CreateNaCl:
    Type: 'AWS::EC2::NetworkAcl'
    Properties:
      VpcId: !Ref 'CreateCapricaVpc'
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'

  SubnetANaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      SubnetId: !Ref 'CapricaSubnetA'
  
  SubnetBNaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      SubnetId: !Ref 'CapricaSubnetB'

  SubnetENaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      SubnetId: !Ref 'CapricaSubnetE'
  
  SubnetFNaClAssociation:
    Type: 'AWS::EC2::SubnetNetworkAclAssociation'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      SubnetId: !Ref 'CapricaSubnetF'

  NaClRule100:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 100
      Protocol: -1
      RuleAction: deny
      CidrBlock: '45.142.120.0/24'

  NaClRule101:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 101
      Protocol: -1
      RuleAction: deny
      CidrBlock: '212.70.149.0/24'

  NaClRule102:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 102
      Protocol: -1
      RuleAction: deny
      CidrBlock: '141.98.80.0/24'

  NaClRule103:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 103
      Protocol: -1
      RuleAction: deny
      CidrBlock: '141.98.10.0/24'

  NaClRule104:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 104
      Protocol: -1
      RuleAction: deny
      CidrBlock: '5.188.206.204/32'

  NaClRule105:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 105
      Protocol: -1
      RuleAction: deny
      CidrBlock: '193.169.254.0/24'

  NaClRule106:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 106
      Protocol: -1
      RuleAction: deny
      CidrBlock: '185.234.219.0/24'

  NaClRule107:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 107
      Protocol: -1
      RuleAction: deny
      CidrBlock: '103.253.42.0/24'

  NaClRule108:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 108
      Protocol: -1
      RuleAction: deny
      CidrBlock: '194.61.53.0/24'

  NaClRule500:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 500
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'

  NaClRule501:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      RuleNumber: 501
      Protocol: -1
      RuleAction: allow
      Ipv6CidrBlock: '::/0'

  NaClEgressRule100:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      Egress: true
      RuleNumber: 100
      Protocol: -1
      RuleAction: allow
      CidrBlock: '0.0.0.0/0'

  NaClEgressRule101:
    Type: 'AWS::EC2::NetworkAclEntry'
    Properties:
      NetworkAclId: !Ref 'CreateNaCl'
      Egress: true
      RuleNumber: 101
      Protocol: -1
      RuleAction: allow
      Ipv6CidrBlock: '::/0'

Outputs:
  CapricaVpcId:
    Value: !Ref CreateCapricaVpc
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'CreateCapricaVpc' ]]
