Description: Deployment of Galactica Security Group
Parameters:
  deployDate:
    Type: String
    Description: Date for the deployment
    Default: 1970-01-01 00:00:00
  commitSha: 
    Type: String
    Description: Git commit SHA
    Default: nocommit
  galacticaIp:
    Type: String
    Description: IP4 address for galactica (or whatever IP address you want to allow)
    Default: 127.0.0.1
    AllowedPattern: ^\d{1,3}.\d{1,3}.\d{1,3}.\d{1,3}$

Resources:
  galacticaSG:
    Type: 'AWS::EC2::SecurityGroup'
    DeletionPolicy: Retain
    Properties:
      GroupDescription: Allow all traffic from galactica
      GroupName: galactica All Traffic [managed]
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: !Join ['', [!Ref 'galacticaIp', '/32'] ]
      Tags:
        - Key: managedBy
          Value: !Join ['-', ['CloudFormationDeployment', !Ref 'commitSha'] ]
        - Key: deployDate
          Value: !Ref 'deployDate'

Outputs:
  galacticaSGId:
    Value: !GetAtt galacticaSG.GroupId
    Export: 
      Name: !Join [':', [ !Ref 'AWS::StackName', 'galacticaSG' ]]
